# Generated by Django 4.2.7 on 2025-03-25 22:14

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified_user_microsoft_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='work_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=accounts.models.default_work_days, size=None),
        ),
    ]
