services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=meeting_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - backend_venv:/opt/venv
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - GOOGLE_CLIENT_ID=22230288681-hcv9cs7uqe3273419fpiiokrvlj42a2o.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - FRONTEND_URL=http://localhost:3000
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=1
      - EMAIL_HOST_USER=sunil.singh.programmer@gmail.com
      - EMAIL_HOST_PASSWORD=fmka pecd bzgl mfdm
      - DEFAULT_FROM_EMAIL=sunil.singh.programmer@gmail.com
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_MICROSOFT_CLIENT_ID=d18a0b19-053b-4d22-862d-4808c1f52af2
      - NEXT_PUBLIC_MICROSOFT_TENANT_ID=consumers
      - NEXT_PUBLIC_MICROSOFT_REDIRECT_URI=http://localhost:3000/auth/microsoft/callback
      - NEXT_PUBLIC_MICROSOFT_SCOPE=openid profile email offline_access User.Read
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  backend_venv:
    driver: local

networks:
  app-network:
    driver: bridge